from collections.abc import Mapping, Sequence
from typing import Final, final
__version__: Final[str]

@final
class ActorInfo:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def actor_id(self, /) -> bytes: ...
    @property
    def driver_actor_host(self, /) -> str: ...
    @property
    def driver_actor_port(self, /) -> int: ...
    @property
    def name(self, /) -> str: ...
    @property
    def owner_node_id(self, /) -> bytes: ...
    @property
    def owner_pid(self, /) -> int: ...
    @property
    def registered_at_unix_ms(self, /) -> int: ...

@final
class Address:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, host: str, port: int, worker_id_bytes: Sequence[int]) -> Address: ...
    def __reduce__(self, /) -> tuple[object, tuple[object, ...]]: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def host(self, /) -> str: ...
    def is_resolved(self, /) -> bool: ...
    @staticmethod
    def nil() -> Address: ...
    @property
    def port(self, /) -> int: ...
    @property
    def worker_id(self, /) -> bytes: ...

@final
class ErrorCategory:
    ActorDied: Final[ErrorCategory]
    FetchTimeout: Final[ErrorCategory]
    ObjectLost: Final[ErrorCategory]
    ObjectUnreconstructable: Final[ErrorCategory]
    OutOfMemory: Final[ErrorCategory]
    OwnerDied: Final[ErrorCategory]
    RuntimeEnvFailed: Final[ErrorCategory]
    TaskCancelled: Final[ErrorCategory]
    TaskException: Final[ErrorCategory]
    Unschedulable: Final[ErrorCategory]
    WorkerDied: Final[ErrorCategory]
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class ErrorInfo:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, category: ErrorCategory, message: str, traceback: str |None = None, raw_code: int = 0) -> ErrorInfo: ...
    def __repr__(self, /) -> str: ...
    @property
    def category(self, /) -> ErrorCategory: ...
    @property
    def message(self, /) -> str: ...
    @property
    def raw_code(self, /) -> int: ...
    @property
    def traceback(self, /) -> str |None: ...

@final
class JobInfo:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def driver_host(self, /) -> str: ...
    @property
    def driver_pid(self, /) -> int: ...
    @property
    def finished_at_unix_ms(self, /) -> int: ...
    @property
    def job_id(self, /) -> bytes: ...
    @property
    def node_id(self, /) -> bytes: ...
    @property
    def registered_at_unix_ms(self, /) -> int: ...
    @property
    def status(self, /) -> str: ...

@final
class NodeInfo:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def host(self, /) -> str: ...
    @property
    def last_heartbeat_unix_ms(self, /) -> int: ...
    @property
    def node_id(self, /) -> bytes: ...
    @property
    def plasma_socket(self, /) -> str: ...
    @property
    def port(self, /) -> int: ...
    @property
    def registered_at_unix_ms(self, /) -> int: ...
    @property
    def resources(self, /) -> Resources: ...
    @property
    def status(self, /) -> str: ...

@final
class ObjectId:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, bytes: Sequence[int]) -> ObjectId: ...
    def __reduce__(self, /) -> tuple[object, tuple[object, ...]]: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def for_return(task_bytes: Sequence[int], return_index: int) -> ObjectId: ...
    @property
    def hex(self, /) -> str: ...
    def is_nil(self, /) -> bool: ...
    @staticmethod
    def nil() -> ObjectId: ...
    @staticmethod
    def random() -> ObjectId: ...
    @property
    def return_index(self, /) -> int: ...
    def to_bytes(self, /) -> bytes: ...

@final
class ObjectRef:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, object_id: ObjectId, owner: Address, owner_node_id: Sequence[int] |None = None) -> ObjectRef: ...
    def __reduce__(self, /) -> tuple[object, tuple[object, ...]]: ...
    def __repr__(self, /) -> str: ...
    def exception(self, /) -> object |None: ...
    @property
    def hex(self, /) -> str: ...
    def is_failed(self, /) -> bool: ...
    def is_ready(self, /) -> bool: ...
    @property
    def object_id(self, /) -> ObjectId: ...
    @property
    def owner(self, /) -> Address: ...
    @property
    def owner_node_id(self, /) -> bytes |None: ...
    def peek_error(self, /) -> ErrorInfo |None: ...
    def state(self, /) -> RefState: ...

@final
class RefState:
    Failed: Final[RefState]
    Pending: Final[RefState]
    ReadyLocal: Final[RefState]
    ReadyRemote: Final[RefState]
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def is_failed(self, /) -> bool: ...
    def is_ready(self, /) -> bool: ...

@final
class Resources:
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, num_cpus: int = 0, num_gpus: int = 0, memory_bytes: int = 0) -> Resources: ...
    def __repr__(self, /) -> str: ...
    @property
    def memory_bytes(self, /) -> int: ...
    @property
    def num_cpus(self, /) -> int: ...
    @property
    def num_gpus(self, /) -> int: ...

def _evict_local(object_id: Sequence[int]) -> None: ...
def _is_spilled(object_id: Sequence[int]) -> bool: ...
def _lineage_status_str(object_id: Sequence[int]) -> str: ...
def _lookup_named_actor(name: str) -> ActorInfo |None: ...
def _mint_actor_result_ref(owner_node_id: Sequence[int] |None = None) -> ObjectRef: ...
def _plasma_socket_path() -> str: ...
def _pool_pending() -> int: ...
def _record_plasma_seal(object_id: Sequence[int], metadata: Sequence[int], data_size: int) -> None: ...
def _register_named_actor(name: str, actor_id: Sequence[int], driver_actor_host: str = "", driver_actor_port: int = 0) -> None: ...
def _spill_object(object_id: Sequence[int]) -> bool: ...
def _unregister_named_actor(name: str, actor_id: Sequence[int]) -> None: ...
def _worker_seal(object_id: Sequence[int], metadata: Sequence[int], data: Sequence[int]) -> int: ...
def cluster_session_id() -> bytes |None: ...
def fetch_object(object_id: Sequence[int], owner_node_id: Sequence[int]) -> None: ...
def free(refs: Sequence[object]) -> None: ...
def get(refs: object, timeout: float |None = None) -> object: ...
def get_object_locations(object_id: Sequence[int]) -> list[object]: ...
def get_settled(refs: Sequence[object], timeout: float |None = None) -> list[object]: ...
def init(address: str |None = None) -> None: ...
def is_initialized() -> bool: ...
def job_id() -> bytes |None: ...
def list_actors() -> list[object]: ...
def list_jobs() -> list[object]: ...
def list_nodes() -> list[object]: ...
def local_raylet_address() -> tuple[str, int] |None: ...
def node_id() -> bytes |None: ...
def node_status_local(node_id: bytes) -> str |None: ...
def pull_object(host: str, port: int, object_id: Sequence[int]) -> tuple[bytes, bytes]: ...
def push_object(host: str, port: int, object_id: Sequence[int], metadata: Sequence[int], data: Sequence[int]) -> None: ...
def put(value: object) -> ObjectRef: ...
def register_object(object_id: Sequence[int], holder_node_id: Sequence[int]) -> None: ...
def shutdown() -> None: ...
def state(refs: Sequence[object]) -> dict[object, object]: ...
def submit_task(callable: object, args: tuple[object, ...], kwargs: Mapping[str, object] |None = None, num_returns: int = 1) -> list[object]: ...
def try_resubmit_for_lineage(object_id: Sequence[int]) -> bool: ...
def wait(refs: Sequence[object], num_returns: int = 1, timeout: float |None = None) -> tuple[object, ...]: ...
def wait_with_states(refs: Sequence[object], timeout: float |None = None) -> dict[object, object]: ...

__all__ = ['__version__', 'ActorInfo', 'Address', 'ErrorCategory', 'ErrorInfo', 'JobInfo', 'NodeInfo', 'ObjectId', 'ObjectRef', 'RefState', 'Resources', '_evict_local', '_is_spilled', '_lineage_status_str', '_lookup_named_actor', '_mint_actor_result_ref', '_plasma_socket_path', '_pool_pending', '_record_plasma_seal', '_register_named_actor', '_spill_object', '_unregister_named_actor', '_worker_seal', 'cluster_session_id', 'fetch_object', 'free', 'get', 'get_object_locations', 'get_settled', 'init', 'is_initialized', 'job_id', 'list_actors', 'list_jobs', 'list_nodes', 'local_raylet_address', 'node_id', 'node_status_local', 'pull_object', 'push_object', 'put', 'register_object', 'shutdown', 'state', 'submit_task', 'try_resubmit_for_lineage', 'wait', 'wait_with_states']
